### ISSUE TITLE
libgttk.so error

### ISSUE THREAD

**Issue by beucismis** [TkinterEP/python-gttk#2]
```
Traceback (most recent call last):
  File "/home/adil/Projects/tkodo/tkodo/test.py", line 6, in <module>
    gttk = GTTK(window, theme="Adwaita-dark")
  File "/home/adil/.local/lib/python3.9/site-packages/gttk/__init__.py", line 71, in __init__
    self.tk.call("package", "require", "ttk::theme::gttk")
_tkinter.TclError: couldn't load file "/home/adil/.local/lib/python3.9/site-packages/gttk/libgttk.so": /home/adil/.local/lib/python3.9/site-packages/gttk/libgttk.so: cannot open shared object file: No such file or directory
```

**Comment by rdbende** [comment]
I got the same error message. In `/home/user/.local/lib/python3.9/site-packages/gttk/` there are only `.dll` files that don't work under Linux. 😕

**Comment by beucismis** [comment]
So?

**Comment by rdbende** [comment]
So I couldn't fix it yet.

**Comment by rdbende** [comment]
I just noticed this in the README:

> ### Wheels

> Currently, wheels are provided for Windows. The Linux wheels are built with Travis-CI and are thus not manylinux wheels. Therefore, building yourself is recommended when using Linux (either from the source dist from PyPI or this repository). Feel free to open an issue if you encounter any problems building!
